from odoo import models, fields, api

class claimentry1(models.Model):
    _name = 'claimentry'

    name = fields.Char(string="No.")
    date1 = fields.Date(string="Date")
    clientname = fields.Char(string="Client Name")
    insurername = fields.Char(string="Insurer Name")
    groupname = fields.Char(string="Group Name")
    insurerbranch = fields.Char(string="Insurer Branch")
    policytype = fields.Char(string="Policy Type")
    issuedate = fields.Date(string="Issue Date")
    policyno = fields.Char(string="Policy No.")
    startfrom = fields.Date(string="Start From")
    expiry = fields.Date(string="Expiry")
    suminsured = fields.Char(string="Sum Insured")
    share = fields.Float(string="Share")
    netamount = fields.Float(string="Net Premium")
    claimtype = fields.Selection([('forall','For All')], string="Claim Type")
    claimid = fields.Char(string="Claim ID")
    date2 = fields.Date(string="Date")
    dateof = fields.Date(string="Date of Intimation")
    insurername1 = fields.Char(string="Insurer Name")
    concernedper = fields.Char(string="Concerned Person")
    concerper = fields.Char(string="Concerned Person")
    contact = fields.Char(string="Contact No.")
    contact1 = fields.Char(string="Contact No.")
    email = fields.Char(string="Email ID")
    email1 = fields.Char(string="Email ID")
    insuredname = fields.Char(string="Insured Name")
    conperson = fields.Char(string="Concerned Person")
    conperson1 = fields.Char(string="Concerned Person")
    cont1 = fields.Char(string="Contact No.")
    cont2 = fields.Char(string="Contact N0.")
    emailid = fields.Char(string="Email ID")
    emailid1 = fields.Char(string="Email ID")
    empname = fields.Char(string="Employee Name")
    empcode = fields.Char(string="Employee Code")
    empcont = fields.Char(string="Employee Contact No.")
    emplocation = fields.Char(string="Employee Location")
    empemailid = fields.Char(string="Employee Email ID")
    idissue = fields.Char(string="ID Issu. by Insurer /TPA")
    claimid1 = fields.Char(string="Claim ID")
    admissiondate = fields.Date(string="Admission Date")
    dischargedate = fields.Date(string="Discharge Date")
    patient = fields.Char(string="Patient Name")
    relationwith = fields.Selection([('spouse','Spouse'),('son','Son'),('sonin','Son in Law'),('daughter','Daughter'),('dauin','Daughter in Law'),('self','Self'),('brother','Brother'),('broin','Brother in Law'),('sis','Sister'),('sisin','Son in Law'),('father','Father'),('fatherin','Father in Law'),('mother','Mother in Law'),('motherin','Mother in Law')],string="Relation with Empl.")
    primary = fields.Text(string="Primary Dignosis")
    final = fields.Text(string="Final Dignosis")
    claimamount = fields.Integer(string="Claim Amount")
    remark = fields.Text(string="Remarks")
