from odoo import models, fields, api

class clientcreation1(models.Model):
    _name = 'clientcreation'

    name = fields.Many2one('res.better.zip',string="Location")
    pos = fields.Char(string="POS")
    ppos = fields.Char(string="P-POS")
    rmname = fields.Char(string="RM Name")
    customertype = fields.Selection([('corporate','Corporate'),('retail','Retail'),('retailin','Retail In Corporate')],string="Customer Type")
    reference = fields.Char(string="Reference")
    telecaller = fields.Char(string="Telecaller")
    csc = fields.Char(string="CSC")
    smname = fields.Char(string="SM Name")
    customergroup = fields.Char(string="Customer Group")
    occupation = fields.Char(string="Occupation")
    typeof = fields.Selection([('partnership','Partnership Firm'),('govt','Govt. Company'),('private','Private Limited'),('society','Society/Trust/AOP'),('other','Others'),('proprietorship','Proprietorship Firm'),('public','Public Limited'),('not','Not Available')], string="Type of Organisation")
    industry = fields.Selection([('notavai','Not Available'),('finance','Finance Company'),('service','Service Providers'),('shop','Shopkeepers'),('real','Real Estate'),('professionals','Professionals'),('traders','Traders'),('trans','Transporters'),('commission','Commission Agent'),('manufacture','Manufacturing Concern'),('educa','Educational Institute'),('other','Others')], string="Industry Type")
    customergrow = fields.Selection([('notavail','Not Available'),('very','Very High'),('high','High'),('medium','Medium'),('low','Low')], string="Customer Networth")
    title = fields.Selection([('mr','Mr'),('mrs','Mrs'),('dr','Dr'),('brig','Brig'),('ms','Ms'),('m/s','M/S'),('col','Col.'),('capt','Capt.')], string="Title")
    customernamed = fields.Char(string="CustomerName(D)")
    customernamep = fields.Char(string="CustomerName(P)")
    salutation = fields.Selection([('dear','Dear')], string="Salutation")
    nickname = fields.Char(string="Nick Name")
    gender = fields.Selection([('male','Male'),('female','Female')])
    dateofbirth = fields.Date(string="Date of Birth")
    dateofgreeting = fields.Date(string="Date of Birth(Greetings")
    marriageanni = fields.Date(string="Marriage Anniversary")
    paidup = fields.Float(string="Paid-Up Capital(INR)")
    other = fields.Char(string="Other")
    website = fields.Char(string="Website")
    rm = fields.Char(string="Select RM")
    sm = fields.Char(string="SM")
