# -*- coding: utf-8 -*-
{
    'name': "ecom_lms",

    'summary': """
        Custom Module for Ecom LMS""",

    'description': """
        Custom Module for Ecom LMS
    """,

    'author': "Siddhant Sinha, Meenakshi Sharma, Deepak Chaudhary, Swastik Maurya",
    'website': "http://www.oodlestechnologies.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base', 'web', 'base_user_role', 'website_slides', 'website', 'contacts', 'survey','mass_mailing','mail'],

    # always loaded
    'data': [
        
        'data/ir_module_category.xml',
        'security/user_group.xml',
        'security/ir.model.access.csv',
        'data/email_template.xml',
        
        'data/cron.xml',
        'views/sequence_view.xml',
        'views/user_login_view.xml',
        'views/pwa_course_card_view.xml',
        'views/lms_content_pdf_view_page.xml',
        'views/lms_content_view_page1.xml',
        'views/survey_print_template.xml',
        'views/portal_template.xml',
        'views/pwa_notification_template_view.xml',
        'wizard/course_title_translation_wiz_view.xml',
        'wizard/lesson_title_translation_view.xml',
        'wizard/slide_question_translation_view.xml',
        'wizard/slide_answer_translation_view.xml',
        'wizard/lesson_invite_view.xml',
        'views/course_view.xml',
        'views/survey_view.xml',
        'views/survey_report_template.xml',
        'views/certification_template_view.xml',
        'views/upload_users_view.xml',
        # 'views/assets.xml',
        'views/candidate.xml',
        'views/quiz_template.xml',
        'views/all_quizzes_template.xml',
        'views/employee.xml',
        'views/customer.xml',
        'views/lesson_view.xml',
        'views/main_journey_view.xml',
        # 'views/download.xml',
        'views/my_account.xml',
        # 'wizard/upload_certificate_quiz_view.xml',
        'views/survey_question_view.xml',

        'views/privacy_policy_terms.xml',
        'views/privacy_policy_page.xml',
        'views/setting.xml',
        'views/question_view.xml',
        'views/course_category.xml',
        'views/slide_quizzes.xml',
        'views/course_journey_partner_view.xml',
        'views/course_language.xml',
        'views/website_form.xml',
        'views/user.xml',
        'views/employee_with_most_certification_template.xml',
        'views/employee_with_most_completed_course.xml',
        'views/templates.xml',
        'views/all_journey_template.xml',
        'views/term_services_page.xml',
        'views/courses_all.xml',
        'views/mails_template.xml',
        'views/course.xml',
        'views/lms_example_view.xml',
        'views/lms_example_view1.xml',
        'views/lms_example_view2.xml',
        'views/lms_filter_desktop_view.xml',
        'views/course_view_all_templates.xml',
        'views/featured_courses_view_all_templates.xml',
        'views/explore_all_course_view_templates.xml',
        'views/journey_all_view_templates.xml',
        'views/my_homepage.xml',
        # 'views/lms_example_view.xml',
        'views/course_journey_view.xml',
        'wizard/customer_registeration_wizard.xml',
        'wizard/create_temporary_account.xml',
        'wizard/message_wizard.xml',
        'wizard/band_module_wise_coverage_report_view.xml',
        'wizard/course_liked_report_view.xml',

        # 'views/state_view.xml',

        # 'wizard/delayed_course_list_view.xml',
        'wizard/total_time_spent_report_wizard.xml',
        'views/state_view.xml',

        'wizard/region_wise_report_view.xml',
        'wizard/employee_wise_coverage_report_view.xml',
        'wizard/error_per_module_wise_report_view.xml',
        'wizard/import_users_view.xml',
        'wizard/track_course_completion_view.xml',
        'wizard/assessment_score_report_view.xml',
        'wizard/export_review_report_view.xml',
        'views/custom_web_slides_template_course.xml',

        'views/home_page.xml',
        'views/user_profile_template.xml',
        'views/main_quiz_view.xml',
        'views/inherited_course_card_view.xml',
        'views/quiz_detail_view.xml',
        'views/quiz_partner_view.xml',
        'views/independent_quizzes_report.xml',
        'views/recommend_or_share_template.xml',
        'views/custom_survey_report_certification.xml',
        'views/custom_template_one.xml',
        'views/custom_template_two.xml',
        'views/custom_template_three.xml',
        'views/custom_template_four.xml',
        'views/custom_template_five.xml',
        'views/custom_template_six.xml',
        'views/custom_template_seven.xml',
        'views/custom_template_eight.xml',
        'views/custom_template_nine.xml',
        'views/custom_template_ten.xml',
        'views/custom_template_eleven.xml',
        'views/custom_template_twelve.xml',
        'views/custom_template_thirteen.xml',
        'views/custom_template_fourteen.xml',
        'views/custom_template_fifteen.xml',
        'views/report.xml',
        'report/course_content_view.xml',

        # 'views/custom_template_one.xml',
        # 'views/custom_survey_report_certification.xml',
        'views/total_time_spent_report.xml',


    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
